### PR TITLE
Fix check alert

### LINKED ISSUE #101: White/Black King in Check alert does not render after capturing a piece
Steps to repeat:
-Capture an opposing piece that would allow your piece to put the enemy king in check
-Witness there is no alert message

We should be able to solve this by adding to or changing the logic in the piece#update action.

### PR DESCRIPTION
**Pull request by shanesfast**
Fixes #101 

-Removed a line in `check_test` which was causing issues with alerting for check when an enemy piece was captured which in turn put the enemy king in check. 

-Removed some white space

-Added a spec to show that a game would be in check after an enemy piece is captured which in turn puts the enemy king in check.

### CODE REVIEW

File: app/controllers/pieces_controller.rb [hunk 1]
```diff
@@ -101,7 +101,6 @@ def game_has_two_players?(game)
 
   def check_test(piece, x, y)
     return false if piece.can_take?(helpers.get_piece(x, y, piece.game)) && piece.type == 'King'
-    return false if piece.can_take?(helpers.get_piece(x, y, piece.game)) && !piece.puts_self_in_check?(x, y)
```
Comment (euruswagner) [inline app/controllers/pieces_controller.rb]: I am always hesitant to delete things after previous mistakes being to aggressive. I don't know if we want to comment out just to make sure this is not supposed to catch some other scenario we did not think of. 
`piece.can_take?(helpers.get_piece(x, y, piece.game))` is checking if the piece being moved can take the piece at the target destination. 
`!piece.puts_self_in_check?(x, y)` is checking to make sure it does not leave the player that is moving the opposing player into check at the end of the turn thus making the move invalid. 
So yes it would like this is not necessary since this could lead to a situations where the check_test returns false when in fact it is putting the opposing player in check and should return true.

File: spec/controllers/pieces_controller_spec.rb [hunk 2]
```diff
@@ -147,13 +147,30 @@
...
+
+      black_rook.move_to!(0, 5)
+      white_pawn.reload
+      black_rook.reload
+      @game.reload
+
+      expect(black_rook.x_position).to eq 0
+      expect(black_rook.y_position).to eq 5
+      expect(@game.check?(!black_rook.is_white?)).to eq true
+    end
```
Comment (euruswagner) [inline spec/controllers/pieces_controller_spec.rb]: Since this does not actually check the update function it should probably be moved to its own describe block. Also since the changes were to the `check_test` method should probably change line 172 to something along the lines of
`expect(check_test(black_rook, 0, 5).to eq true`
Perhaps an extra line of testing to also check for the correct flash message. This is going to be wrong but along the lines of:
`expect(flash.message).to eq 'White King in Check.'

To be frank looks like we missed the boat completely on testing the whole `check_test`. That is on all of us. This will tie into some earlier comment because as I review the method it seems like there is definitely some situations that could be a problem.

File: app/controllers/pieces_controller.rb [hunk 3]
```diff
@@ -101,7 +101,6 @@ def game_has_two_players?(game)
...
 
     if piece.puts_self_in_check?(x, y)
       flash.now[:alert] << 'You cannot put/leave yourself in Check.'
```
Comment (euruswagner) [inline app/controllers/pieces_controller.rb]: Okay can't comment any further down then this because no changes were committed further down but as I look at this if statement this seems like it should be the first check in the check_test method. (or better yet moved to the `valid_move?` method) Having this further down means someone could leave themselves open to ending the turn in check. Which leads to all sorts of problems.

File: app/controllers/pieces_controller.rb (hunk 1 above)
Comment (shanesfast) [reply app/controllers/pieces_controller.rb]: In this case I am not worried about deleting this line. It was an oversight on my part from back then. We have the same safeguard further down in this method that would catch a circumstance where a payer might put themselves in check by taking an enemy piece. 

````
if piece.puts_self_in_check?(x, y)
      flash.now[:alert] << 'You cannot put/leave yourself in Check.'
      return false
    end
```

File: app/controllers/pieces_controller.rb [hunk 4]
```diff
@@ -101,7 +101,6 @@ def game_has_two_players?(game)
 
   def check_test(piece, x, y)
     return false if piece.can_take?(helpers.get_piece(x, y, piece.game)) && piece.type == 'King'
```
Comment (euruswagner) [inline app/controllers/pieces_controller.rb]: As I suggested elsewhere just as I am reviewing this popped up for me so figured should at least ask about it.
`piece.can_take?(helpers.get_piece(x, y, piece.game))` This should always return true since this would happen after the `valid_move?` check in the update action.
`piece.type == 'King' checks if the piece being moved is a king? (or perhaps if the piece being taken is king but pretty sure this is testing if piece being moved is a king.
This seems to suggest if you tried you could move a king into check since this would return false before the if statement on line 105/106 returned false with a flash message that prevents the `move_to!` method from happening on line 14 of pieces_controller.rb.

File: spec/controllers/pieces_controller_spec.rb (hunk 2 above)
Comment (shanesfast) [reply spec/controllers/pieces_controller_spec.rb]: I put this spec in update because it is testing functionality that is within the `piece#update` method. Unfortunately you cannot call `check_test` within this spec as it is a private method for `pieces_controller`. 

As far as the flash goes, I know you can check the message in a feature spec but testing for a flash message in controller spec is not so easy. I don't think it's necessary in this case either. We could write a feature spec to make sure it displays but the only thing I really care about here is that the game is in check (which means the flash does have the message, because our update action revolves around the flash messages).  

A lot of the `check_test` method is tested within `pieces_controller_spec.rb`. We don't have any specs explicitly for that method, but that method is heavily integrated in the `piece#update` action. Once again, we could write some tests but I don't think it is necessary. If you think of any specs that could cover a feature of the app we missed then I am all for it.

File: app/controllers/pieces_controller.rb (hunk 3 above)
Comment (shanesfast) [reply app/controllers/pieces_controller.rb]: The order for the first two lines doesn't matter. One is checking to see if a king piece can get itself out of check and the other is to ensure that you are not putting yourself into check when moving a piece. 

I think this is fine where it is, as it is a test to see if you would be put in check, a check test. 

This line `return false unless piece.puts_enemy_in_check?(x, y)` needs to stay towards the bottom as we do not want the method to return false if a move doesn't always put the enemy in check. 

I'm not really sure how having this line where it is could lead to any problems. If you notice any let me know and we can fix it.

File: app/controllers/pieces_controller.rb (hunk 1 above)
Comment (euruswagner) [reply app/controllers/pieces_controller.rb]: As stated down below that safeguard should be moved either to the top or into `valid_move?` because their is a situation where it would return false but allow a king to be moved into check (I believe). And yes I would be fine with deleting it. I also find going back and looking at old code I have written to be not good for my ego.

File: app/controllers/pieces_controller.rb (hunk 4 above)
Comment (shanesfast) [reply app/controllers/pieces_controller.rb]: Yes it is checking if the piece being moved is a king. 
This method would not allow a king to take a piece that would then put it into check due to the next line of code:

```
    if piece.puts_self_in_check?(x, y)
      flash.now[:alert] << 'You cannot put/leave yourself in Check.'
```

Comment (shanesfast) [reply app/controllers/pieces_controller.rb]: `valid_move?` for each piece model does not check if it is an enemy piece on the current tile. `can_take?` does.

File: app/controllers/pieces_controller.rb (hunk 3 above)
Comment (shanesfast) [reply app/controllers/pieces_controller.rb]: Also `valid_move?` is different for each piece model. We would have to add this functionality to every model. I think it is better sitting inside one method.

File: spec/controllers/pieces_controller_spec.rb (hunk 2 above)
Comment (euruswagner) [reply spec/controllers/pieces_controller_spec.rb]: By using `black_rook.move_to!(0, 5)` on line 165 you are completely avoiding the `check_test` method be called. It is only called if you run a put request. https://mixandgo.com/learn/3-ways-of-testing-private-methods-in-rails talks about some ways to test private methods in RSpec. All come with some pros and cons. And for the sake of simplicity we could just instead of using the `move_to!` method on line 165 we could use:
`put :update, params: { id: black_rook.id, x_position: 0, y_position: 5, format: :js }`
I do think this will actually lead to an error because it is not blacks turn so add this on line 162:
`move = create(:move, game_id: @game.id, piece_id: white_pawn.id, start_piece: 5)`
Not for sure if it works with this being entangled with JS but then can add:
`expect(flash[:alert]).to eq 'White King in Check.'`

File: app/controllers/pieces_controller.rb (hunk 1 above)
Comment (shanesfast) [reply app/controllers/pieces_controller.rb]: See comments for lines 102/103. 

Live and learn!

File: app/controllers/pieces_controller.rb (hunk 4 above)
Comment (euruswagner) [reply app/controllers/pieces_controller.rb]: `valid_move?` checks if your own piece is on the destination tile which is the exact same as checking if you can take a piece on the destination tile. Refer to line 11 of piece.rb `if players_own_piece_is_there?(x, y)`.

Comment (euruswagner) [reply app/controllers/pieces_controller.rb]: Since 103 is a return line 105 that checks for putting in check would never be reached.

File: app/controllers/pieces_controller.rb (hunk 1 above)
Comment (euruswagner) [reply app/controllers/pieces_controller.rb]: I do not know what you are saying here?

File: spec/controllers/pieces_controller_spec.rb (hunk 2 above)
Comment (shanesfast) [reply spec/controllers/pieces_controller_spec.rb]: `put :update, params: { id: black_rook.id, x_position: 0, y_position: 5, format: :js }`
I tried this off the bat, but it doesn't seem to want to update the x and y position. 

I am not trying to test the `check_test` method with this spec though. I am simply trying to make sure the state of the game is in check after taking an enemy piece and putting the enemy king in check, which it is. 

`expect(flash[:alert]).to eq 'White King in Check.'` returns nil no matter if I use `move_to!` or the `put :update, params:` line.

File: app/controllers/pieces_controller.rb (hunk 1 above)
Comment (shanesfast) [reply app/controllers/pieces_controller.rb]: I was replying to your ` I also find going back and looking at old code I have written to be not good for my ego.` and telling you to go look at the comment section for lines 102 and 103 (they are pretty much the same conversation here)

File: app/controllers/pieces_controller.rb (hunk 3 above)
Comment (euruswagner) [reply app/controllers/pieces_controller.rb]: I would agree with that. You could move inside is obstructed since every piece calls that method. (except for King so 2 vs 1 and that means it is still better here).

File: app/controllers/pieces_controller.rb (hunk 4 above)
Comment (shanesfast) [reply app/controllers/pieces_controller.rb]: Ahh yea, you are right about the return on line 103. Not sure why I wasn't thinking about that. I will update the PR and switch those lines.

File: app/controllers/pieces_controller.rb (hunk 3 above)
Comment (euruswagner) [reply app/controllers/pieces_controller.rb]: >  One is checking to see if a king piece can get itself out of check

I do not think line 103 checks if a king can move out of check. It checks whether the piece at the destination tile is of the opposite color allowing it to be take and if the piece being moved is a king.

Comment (euruswagner) [reply app/controllers/pieces_controller.rb]: > This line return false unless piece.puts_enemy_in_check?(x, y) needs to stay towards the bottom as we do not want the method to return false if a move doesn't always put the enemy in check.

This is not true since the first thing we want to do in the `check_test` method is see if it actually puts the opposing player in check. Also all the lines above this also return false so if we wanted this to return true before false it would need to be moved down. But again we want this method to return false first thing for the many moves that do not actually put the opposing player in check.

File: spec/controllers/pieces_controller_spec.rb (hunk 2 above)
Comment (euruswagner) [reply spec/controllers/pieces_controller_spec.rb]: Yeah it is not updating the piece because it is whites turn.

File: app/controllers/pieces_controller.rb (hunk 3 above)
Comment (shanesfast) [reply app/controllers/pieces_controller.rb]: Yeap, you are right there about line 103. I'm not even sure if it's necessary now. Because:
```
if piece.puts_self_in_check?(x, y)
      flash.now[:alert] << 'You cannot put/leave yourself in Check.'
      return false
    end
```
would cover the same thing. It doesn't really matter if a piece is a king or not here.

File: spec/controllers/pieces_controller_spec.rb (hunk 2 above)
Comment (euruswagner) [reply spec/controllers/pieces_controller_spec.rb]: Okay makes sense with the JS. As you have stated elsewhere that is an easy check within a game and not really a game breaking bug either way. ie players would laugh if it said white king in check when it is really the black king but would not break the game from functioning.

File: app/controllers/pieces_controller.rb (hunk 3 above)
Comment (euruswagner) [reply app/controllers/pieces_controller.rb]: And sorry saw the change to late. GitHub does not use ActionCable I guess so did not see change till after I posted these comments.

File: spec/controllers/pieces_controller_spec.rb (hunk 2 above)
Comment (shanesfast) [reply spec/controllers/pieces_controller_spec.rb]: Ahh that makes sense. I will update the test and move the white piece, then the black piece.

File: app/controllers/pieces_controller.rb [hunk 5]
```diff
@@ -100,14 +100,12 @@ def game_has_two_players?(game)
...
   def check_test(piece, x, y)
-    return false if piece.can_take?(helpers.get_piece(x, y, piece.game)) && piece.type == 'King'
-    return false if piece.can_take?(helpers.get_piece(x, y, piece.game)) && !piece.puts_self_in_check?(x, y)
-
     if piece.puts_self_in_check?(x, y)
       flash.now[:alert] << 'You cannot put/leave yourself in Check.'
       return false
     end
 
+    return false if piece.can_take?(helpers.get_piece(x, y, piece.game)) && piece.type == 'King'
```
Comment (euruswagner) [inline app/controllers/pieces_controller.rb]: Ahh I think I finally figured this out. Because line 109 would return true even if a king is the one putting the opposing king in check and a king can never put a king in check. I still think this is redundant with moving up the if statement above this because a king could never move itself into check to put an opposing king into check but just happy to figure out what it is there for. We can do whatever with this.

File: spec/controllers/pieces_controller_spec.rb (hunk 2 above)
Comment (shanesfast) [reply spec/controllers/pieces_controller_spec.rb]: Nevermind, it seems that even if I move a white piece first, it is still not updating the black pieces moves.

Comment (shanesfast) [reply spec/controllers/pieces_controller_spec.rb]: This spec is doing what I wanted it to, so I am going to leave it at that.

File: spec/controllers/pieces_controller_spec.rb [hunk 6]
```diff
@@ -147,13 +147,31 @@
...
```
Comment (euruswagner) [inline spec/controllers/pieces_controller_spec.rb]: I still think that this is checking the` check?` method in the game.rb file not the `check_test` method in the update controller since `move_to!` just forces the piece to move it does not check any of the other methods inside the update controller. I will download and work on this test also.

File: app/controllers/pieces_controller.rb (hunk 5 above)
Comment (shanesfast) [reply app/controllers/pieces_controller.rb]: Yeap, I believe that was my reasoning for it. But it is not needed, so I will remove it and see what the specs think.

File: spec/controllers/pieces_controller_spec.rb (hunk 6 above)
Comment (shanesfast) [reply spec/controllers/pieces_controller_spec.rb]: Yes, but `move_to!` and `game.check?` are both called from piece#update. Since this test is updating a piece, I think it fits here. If you come up with something better, by all means push it up.

File: app/controllers/pieces_controller.rb (hunk 5 above)
Comment (shanesfast) [reply app/controllers/pieces_controller.rb]: Removed it and the specs agreed it was ok without it. Simplification!

File: spec/controllers/pieces_controller_spec.rb (hunk 6 above)
Comment (euruswagner) [reply spec/controllers/pieces_controller_spec.rb]: Yup working on it now. And yes the are both called from within piece#update but I do not think that it means it is checking the other methods in piece#update.
